sudo: required
dist: trusty
language: c
os: osx
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
before_install:
- brew update
install:
- nvm install 8
- curl -o- -L https://yarnpkg.com/install.sh | bash
- source ~/.bashrc
- yarn
script:
- yarn run release:predraft
branches:
  only:
  - osx
before_deploy:
  - git config --global user.name "mattRedBox"
deploy:
  provider: releases
  skip_cleanup: true
  github_token:
    secure: KlFxUtB/Ywk6+sJSPa/h2XDeSDQSI+17M38QdDqELxxxbkwPbAwl6mNv88V5+5dmjxZ08CC1owfpfJtdMaHrGZGcFB1aEb3+4jnFl6nmTHxORKRW3CGQcFyKOlq4vyrMD03jDOmGgkeUenu6aarXJoA2H+a/xRE6lonX4epxPApWeNFUTWplHtiQul8zLUxd/mSNcS286QV5npGVt7u+584eBp+M89kDH3awMtZxZejVRkmikSVvEmbjK2y5zkDShhvSJxqt+mBXticIg3iYYpv9wGoK/V1UXNAxuthjvLf7jbmMyuCjhSIw5CujHhmewYG9XY6ACvYg5TaevhV7T3skYNXcYf1HN6y64pEvEL2HBHWh193EXF/hUO6K6u7aqwR/vhggo6Io5fUmzdTfk7OmibDpWaonPpNLLGsaCNcswxaG6gcXwl/CFMxIuy1FA1t60ua9IMqCKtWaHSJ6Qcf+bvtc7SgkqL59USVtdTJJCYRMeySyWbzKNqZe8dqdFTNEF5heF4VEZ4EwNRi9Vfv1QMCwGLOScljlxq9JCgGyuiFRgw5EuMWg98K4MEMas478ao/ykVFXoH6c/T/qzQw9x/c337TIZnino/gXnh9he5lgszYEIYF7XFsAqXNML5bKDCR8Yf9sAAomrd+cD0rAT0Tphx4RWdBGl0otpXY=
  file_glob: true
  api_key:
    secure: QF+dR63h4uhDSziEszy0g9Gbj+Oc3Y3v3k2lLyCmu8fONlrXLIY9I9LBD/tU9mPGlWbQCrjlxG1WbVHLNsPFSg190IbXk8lhl81rQ0PRV/oyyn8zDJoC3wgFXaAY2PwxYfdj+AvwZPEQ54W+zXrdsvDrBqV+jdIXtPtEsRsFXdByYxTT+rA9QbSe4Mc64tSkUlcaIRQH6fwgvLadsTPFj1NhN9xx4cIc1khZhNKPGdhPiFdGlYaA2KfFrEqZZ7tMhZXEVV/ix/nq64go5plzd9F6E8C04sBPLD4beSGLQ1pXHswuAXenQS44DJvrn018JQodjIEcqw9uHuxVnJ3G/BLwfnL+4xEQ0bRN/4oRcC35az6PEMS4M0Y5AfUJ1lqvT/zIx4/3b1em5F+I3ILl1ufxdGxjAHq/IO7UROvcwAo7U7EgFh2+BL6dlNezBakV1M9JMMyMn1smGxB/XWMGPJBXduXDsea5C6osTkW7Numjn8Zk1HqymbWgsG7QnBWQyOdZrLsRmHNb9qS5uDjFeMgOxawMlY73FchmGGq/9JKA2DAGzoZX7vIG2/0COx0ZfahYz7izhWi/Kq72BmfZTD/6oyjGLSWMtE9IGy1yG8bxko8oOF0HJZ980iQLDfX1nGQABGg4XThrZ0PxR9DmwBs1zuRQK4jm3idfwl8L4Ps=
  file: data-curator-*.*.*.dmg
  on:
    repo: ODIQueensland/data-curator
    all_branches: true
    tags: false
